object Versions{
    const val Gradle: String = "7.0.0"
    const val Kotlin: String = "1.4.32"
    const val Coroutines: String = "1.3.8"
    const val Material: String = ""
    const val Hilt: String = "2.33-beta"
    const val HiltNavigation: String = "1.0.0-alpha01"
    const val Accompanist: String = "0.7.1"
    const val AndroidX: String = "1.3.2"
    const val AppCompat: String = "1.3.0-rc01"
    const val ConstraintLayoutCompose: String = "1.0.0-alpha03"
    const val DataStore: String = "1.0.0-alpha08"
    const val Compose: String = "1.0.0-beta01"
    const val ComposeActivity: String = "1.3.0-alpha03"
    const val ComposeViewModel: String = "1.0.0-alpha02"
    const val NavigationCompose: String = "1.0.0-alpha10"
    const val Room: String = "2.3.0-rc01"
    const val Work: String = "2.5.0"
    const val FirebasePerf: String = "19.1.1"
    const val FirebaseAnalytics: String = "18.0.3"
    const val FirebaseCrash: String = "17.4.1"
    const val Retrofit: String = "2.9.0"
    const val OkHttp: String = "4.9.1"
    const val Gson: String = "2.8.6"
    const val LeakCanary: String = "2.7"
    const val Junit: String = "5.7.1"
    const val Mockk: String = "1.11.0"
}